### PR TITLE
Add numeronym

### PR DESCRIPTION
**Pull request by qu1queee**
A silly attempt to use a numeronym for this repo, following all the tooling
around k8s that use a similar one, e.g.:
- k9s
- k3s

## Description
I just want to have a more compacted attractive name for this repo. More in sync to the k8s community.

## Motivation and Context
Similar to the description above.

## How Has This Been Tested?
Is just a README.md change, and my YAML linter did not complain :)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by f0rmiga** [comment]
I think `k4f` is a misnomer. The `4` is usually used as a reduction of `for`.
If `kcf` is any better, I could buy the idea.

**Comment by qu1queee** [comment]
Not an stronger fan of `kcf`, due to its resemblance to kfc(food).

**Comment by f0rmiga** [comment]
Ping @troytop.

**Comment by troytop** [comment]
I get it, but let's not change this right now. A more accurate numeronym would be cf4k, but that is too different from k9s, k3s et al. `kcf` already exists https://github.com/EngineerBetter/kcf

Closing this PR, but open to further discussion.

**Pull request closed without merging**
