### PR TITLE
Gate PRs on CI

### PR DESCRIPTION
**Pull request by mudler**
This PR it's renaming the post-publish pipeline in "kubecf". It's adding linting and tests for PR and publishing artifacts to s3 bucket

## Description
Concourse will run tests and lint PRs with the "Trigger: CI" label on. The PR also does eirini/diego tests against master

## How Has This Been Tested?
It is deployed currently on https://concourse.suse.dev/teams/main/pipelines/kubecf

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Last. (I hope). Given that the pipeline already uses yaml anchoring and referencing to reduce the amount of duplicate settings, I would like to point to the following commonalities in the config of all the tasks:

```
4x
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: thulioassis/bazel-docker-image
          tag: 2.0.0

12x
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: splatform/catapult

I/O

2x
      inputs:
      - name: kubecf

2x
      inputs:
      - name: kubecf
      outputs:
      - name: output

7x
      inputs:
      - name: kubecf
      - name: catapult
      outputs:
      - name: output

4x
      inputs:
      - name: catapult
      - name: kubecf
      outputs:
      - name: mail-output

2x
      inputs:
      - name: kubecf
      - name: catapult
      - name: s3.kubecf
      outputs:
      - name: output
```

**Comment by andreas-kupries** [comment]
Still another thing:

I see two styles of specifying `on_success`, `on_failure` using anchors and references.

 - Style 1 uses  anchors `success-*`, `failure-*` and the per-task spec sets/overrides the `context` key.
 - Style 2 uses per-task anchors from the `put:` key, and the s/f specs then override the `state` key.

Can this be unified into a single style ? (Not sure if there are differences necessitating the two styles). Note, assuming unification is possible, I have a tiny preference for Style 1. Mainly because it needs only a two anchors reusable across all tasks (of either master or pr pipelines).

**Comment by andreas-kupries** [comment]
Ok. I rebased #400 to be on top of this one.

Some of the commits are actually changes which could go into this PR.
With my PR on top this should be easy to do.
Assuming that the changes are actually acceptable.
In detail:

  - Commit 5a7220a07ed00313c6ee1016d1d2fecf786bf660 fixes some issues in the base pipeline (borken anchoring/references in the first steps of the PR pipeline), see comment about the 4 definitions of `success-pr`.

    Wrt the two styles I can confirm that this is indeed a difference  of older master vs newer PR pipeline and steps. I have not tried to unify that.

  - Commits 89169069f4676ee57a5d8d456ed874a8b879ee18 and bdb445771bbba522bfc67c6c27620bbfcef8886a tweak the `README.md` a bit. See my comment about the `README.md` here, above.

**Comment by jimmykarily** [comment]
We are debugging an issue with cached resource versions in Concourse but the pipeline looks pretty much as we wanted it to look. One thing still missing is the cleaning up of testing clusters. There is an api endpoint for that in EKCP, we just have to add an [ensure](https://concourse-ci.org/ensure-step-hook.html) step to cleanup.

**Comment by jimmykarily** [comment]
The pipeline has been refactored. PR comments were either addresses or do no longer apply. We will merge this because the pipeline is using the scripts in this PR to test master and PRs and without this merged all PRs will miss the needed files. We can create a new PR with improvements after this is merged.

**Pull request merged**
